import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Dimensions, FlatList, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { GlassView } from 'expo-glass-effect';
import { MenuView } from '@expo/ui/community/menu';
import { supabase } from '@/lib/supabase';

type Tx = { type: string; amount: number; created_at: string; account_id: string };
export default function DashboardPage() {
  const [accounts, setAccounts] = useState<any[]>([]); const [txs, setTxs] = useState<Tx[]>([]); const [refreshing, setRefreshing] = useState(false); const [activeAccount, setActiveAccount] = useState(0);
  const [period, setPeriod] = useState<'all' | '7' | '30' | '90'>('all');
  const load = useCallback(async () => { setRefreshing(true); const { data: { user } } = await supabase.auth.getUser(); if (user) { const [{ data: a }, { data: t }] = await Promise.all([supabase.from('accounts').select('id,name,type,initial_balance').eq('user_id', user.id).eq('is_active', true).order('created_at'), supabase.from('transactions').select('type,amount,created_at,account_id').eq('user_id', user.id).order('created_at', { ascending: true })]); setAccounts(a ?? []); setTxs((t ?? []) as Tx[]); } setRefreshing(false); }, []);
  useEffect(() => { load(); }, [load]);
  const income = useMemo(() => txs.filter(t => t.type === 'INCOME').reduce((s, t) => s + Number(t.amount), 0), [txs]); const expenses = useMemo(() => txs.filter(t => t.type === 'EXPENSE').reduce((s, t) => s + Number(t.amount), 0), [txs]);
  const accountCards = useMemo(() => accounts.map(a => ({ ...a, balance: Number(a.initial_balance ?? 0) + txs.filter(t => t.account_id === a.id).reduce((s, t) => s + (t.type === 'INCOME' ? Number(t.amount) : -Number(t.amount)), 0) })), [accounts, txs]); const total = accountCards.reduce((s, a) => s + a.balance, 0);
  const filteredTxs = useMemo(() => { if (period === 'all') return txs; const cutoff = Date.now() - Number(period) * 86400000; return txs.filter(t => new Date(t.created_at).getTime() >= cutoff); }, [txs, period]);
  const bars = useMemo(() => Array.from({ length: 7 }, (_, d) => filteredTxs.filter(t => t.type === 'EXPENSE' && new Date(t.created_at).getDay() === d).reduce((s, t) => s + Number(t.amount), 0)), [filteredTxs]); const max = Math.max(...bars, 1);
  const cardWidth = Dimensions.get('window').width - 28; const cardData = accountCards.length ? accountCards : [{ id: 'empty', type: '', name: 'No accounts', balance: total }];
  return <View style={styles.screen}><SafeAreaView style={styles.safe} edges={['top', 'left', 'right']}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={load} />} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><Text style={styles.logo}>Artos</Text><FlatList horizontal pagingEnabled snapToInterval={cardWidth + 12} decelerationRate="fast" showsHorizontalScrollIndicator={false} contentContainerStyle={styles.accountCarousel} data={cardData} keyExtractor={a => a.id} onMomentumScrollEnd={event => setActiveAccount(Math.round(event.nativeEvent.contentOffset.x / (cardWidth + 12)))} renderItem={({ item }) => <GlassView glassEffectStyle="regular" style={[styles.accountCard, { width: cardWidth }]}><Text style={styles.accountType}>{item.type}</Text><Text style={styles.accountName}>{item.name}</Text><Text style={styles.balance}>NT$ {item.balance.toLocaleString()}</Text><View style={styles.dots}>{cardData.map((account, i) => <View key={account.id} style={[styles.dot, i === activeAccount && styles.activeDot]} />)}</View></GlassView>} /></ScrollView><View style={styles.columns}><GlassView glassEffectStyle="regular" style={styles.smallCard}><Text style={styles.smallTitle}>Pengeluaran</Text><Text style={styles.smallAmount}>NT$ {expenses.toLocaleString()}</Text></GlassView><GlassView glassEffectStyle="regular" style={styles.smallCard}><Text style={styles.smallTitle}>Pemasukan</Text><Text style={styles.smallAmount}>NT$ {income.toLocaleString()}</Text></GlassView></View><GlassView glassEffectStyle="regular" style={styles.chartCard}><View style={styles.chartHeader}><Text style={styles.chartTitle}>Grafik</Text><MenuView title="Period" actions={[{ id: 'all', title: 'All Time', state: period === 'all' ? 'on' : 'off' }, { id: '7', title: '7 Days', state: period === '7' ? 'on' : 'off' }, { id: '30', title: '30 Days', state: period === '30' ? 'on' : 'off' }, { id: '90', title: '90 Days', state: period === '90' ? 'on' : 'off' }]} onPressAction={({ nativeEvent }) => setPeriod(nativeEvent.event as typeof period)}><Text style={styles.periodButton}>{period === 'all' ? 'All Time' : `${period} Days`}</Text></MenuView></View><View style={styles.chart}><View style={styles.axis} />{bars.map((v, i) => <View key={i} style={styles.barColumn}><View style={[styles.bar, { height: Math.max(8, 104 * v / max) }]} /><Text style={styles.day}>{['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'][i]}</Text></View>)}</View></GlassView></SafeAreaView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#f4f6f7' }, safe: { flex: 1 }, content: { paddingHorizontal: 14, paddingTop: 12, paddingBottom: 16, gap: 18 }, logo: { fontFamily: 'Georgia', color: '#3484c2', fontSize: 45, fontWeight: 'bold', letterSpacing: -2, marginHorizontal: 16 }, accountCarousel: { gap: 12 }, accountCard: { height: 250, borderRadius: 31, padding: 28, overflow: 'hidden', backgroundColor: 'rgba(218,220,221,0.82)' }, accountType: { color: '#69737a', fontSize: 15, marginBottom: 15 }, accountName: { color: '#20272c', fontSize: 28, fontWeight: '500' }, balance: { color: '#20272c', fontSize: 34, fontWeight: '600', marginTop: 18 }, dots: { flexDirection: 'row', justifyContent: 'center', gap: 7, marginTop: 'auto' }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#c7cdd1' }, activeDot: { width: 20, backgroundColor: '#3989c4' }, columns: { flexDirection: 'row', gap: 12, marginHorizontal: 14, marginTop: 18 }, smallCard: { flex: 1, minHeight: 130, borderRadius: 28, padding: 20, overflow: 'hidden', backgroundColor: 'rgba(218,220,221,0.82)' }, smallTitle: { color: '#20272c', fontSize: 21, fontWeight: '500' }, smallAmount: { color: '#20272c', fontSize: 22, marginTop: 14, fontWeight: '600' }, chartCard: { minHeight: 230, borderRadius: 31, padding: 26, overflow: 'hidden', backgroundColor: 'rgba(218,220,221,0.82)', margin: 14, marginTop: 18 }, chartHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, chartTitle: { color: '#20272c', fontSize: 22, fontWeight: '500' }, periodButton: { color: '#3989c4', fontSize: 14, fontWeight: '600' }, chart: { height: 145, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginTop: 20, paddingHorizontal: 6 }, axis: { position: 'absolute', bottom: 22, left: 4, right: 4, height: 1, backgroundColor: 'rgba(32,39,44,0.22)' }, barColumn: { height: 130, alignItems: 'center', justifyContent: 'flex-end', gap: 5 }, bar: { width: 19, borderRadius: 10, backgroundColor: '#3989c4' }, day: { color: '#69757d', fontSize: 11 } });
