import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Animated, Keyboard, KeyboardAvoidingView, PanResponder, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, TouchableWithoutFeedback, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { supabase } from '@/lib/supabase';
import type { RecurringExpense } from '@/features/quick/hooks/useRecurringExpenses';

export function RecurringFormSheet({ visible, sheetY, onClose, onSaved, editItem }: { visible: boolean; sheetY: Animated.Value; onClose: () => void; onSaved: () => void; editItem?: RecurringExpense | null }) {
  const insets = useSafeAreaInsets();
  const sheetPan = React.useRef(PanResponder.create({ onMoveShouldSetPanResponder: (_, g) => Math.abs(g.dy) > 6, onPanResponderMove: (_, g) => sheetY.setValue(Math.max(-122, g.dy)), onPanResponderRelease: (_, g) => { if (g.dy > 110 || g.vy > 1) onClose(); else Animated.spring(sheetY, { toValue: g.dy < -35 ? -122 : 0, useNativeDriver: true, damping: 22, stiffness: 220 }).start(); } })).current;
  const [amount, setAmount] = useState('0'); const [name, setName] = useState(''); const [categories, setCategories] = useState<any[]>([]); const [category, setCategory] = useState<any>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!visible) return; (async () => { const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data } = await supabase.from('categories').select('id,name,type').eq('user_id', user.id).eq('is_active', true).order('name'); setCategories(data ?? []); setCategory(data?.find(item => item.id === editItem?.category_id) ?? data?.[0] ?? null); setAmount(editItem ? String(editItem.amount) : '0'); setName(editItem?.name ?? ''); })(); }, [visible, editItem]);
  if (!visible) return null;
  const save = async () => { const { data: { user } } = await supabase.auth.getUser(); const value = Number(amount); if (!user || !category || !name.trim() || !value) return; setSaving(true); if (editItem) await supabase.from('recurring_transactions').update({ category_id: category.id, type: category.type, name: name.trim(), amount: value }).eq('id', editItem.id); else { const { data: accounts } = await supabase.from('accounts').select('id').eq('user_id', user.id).eq('is_active', true).limit(1); await supabase.from('recurring_transactions').insert({ user_id: user.id, account_id: accounts?.[0]?.id, category_id: category.id, type: category.type, name: name.trim(), amount: value, frequency: 'MONTHLY', start_date: new Date().toISOString().slice(0, 10), next_date: new Date().toISOString().slice(0, 10) }); } setSaving(false); onSaved(); onClose(); };
  return <Animated.View {...sheetPan.panHandlers} style={[styles.sheet, { transform: [{ translateY: sheetY }] }]}><KeyboardAvoidingView style={styles.keyboard} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.handle} /><View style={styles.header}><Pressable onPress={onClose}><Text style={styles.cancel}>Cancel</Text></Pressable><Text style={styles.title}>{editItem ? 'Edit Recurring' : 'Recurring Expense'}</Text><Pressable onPress={save} disabled={saving}>{saving ? <ActivityIndicator color="#277cb8" /> : <Text style={styles.save}>{editItem ? 'Save' : 'Add'}</Text>}</Pressable></View><TouchableWithoutFeedback onPress={Keyboard.dismiss} accessible={false}><View style={[styles.content, { paddingBottom: insets.bottom + 24 }]}><Text style={styles.label}>Amount</Text><View style={styles.amountRow}><Text style={styles.currency}>NT$</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" style={styles.amount} /></View><View style={styles.line} /><Text style={styles.label}>Name</Text><TextInput value={name} onChangeText={setName} placeholder="Expense name" placeholderTextColor="#a4adb3" style={styles.input} /><Text style={styles.label}>Category</Text><View style={styles.chips}>{categories.map(item => <Pressable key={item.id} onPress={() => setCategory(item)} style={[styles.chip, category?.id === item.id && styles.activeChip]}><Text style={[styles.chipText, category?.id === item.id && styles.activeText]}>{item.name}</Text></Pressable>)}</View></View></TouchableWithoutFeedback></KeyboardAvoidingView></Animated.View>;
}
const styles = StyleSheet.create({ sheet: { ...StyleSheet.absoluteFill, top: 122, zIndex: 120, backgroundColor: '#f3f6f7', borderTopLeftRadius: 34, borderTopRightRadius: 34 }, keyboard: { flex: 1 }, handle: { width: 70, height: 4, borderRadius: 3, backgroundColor: '#cbd5da', alignSelf: 'center', marginTop: 11 }, header: { height: 62, paddingHorizontal: 23, alignItems: 'center', justifyContent: 'space-between', flexDirection: 'row' }, cancel: { color: '#60717d', fontSize: 16 }, title: { color: '#25313b', fontSize: 20, fontWeight: '700' }, save: { color: '#277cb8', fontSize: 16, fontWeight: '700' }, content: { flex: 1, marginHorizontal: 18, borderRadius: 30, backgroundColor: '#fff', padding: 22 }, label: { color: '#a3adb4', fontSize: 16, marginBottom: 7 }, amountRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center' }, currency: { color: '#2b3740', fontSize: 17, marginRight: 7 }, amount: { minWidth: 145, color: '#29353e', fontSize: 55, textAlign: 'center' }, line: { height: StyleSheet.hairlineWidth, backgroundColor: '#ccd5da', marginVertical: 14 }, input: { color: '#34414b', fontSize: 19, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: '#ccd5da', paddingBottom: 7 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, chip: { paddingHorizontal: 15, paddingVertical: 8, borderRadius: 17, backgroundColor: '#e1e4e6' }, activeChip: { backgroundColor: '#3184c3' }, chipText: { color: '#3f4a54', fontSize: 15 }, activeText: { color: '#fff' } });
